# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_version', models.CharField(max_length=8, verbose_name='The version of the client submitting the report')),
                ('submission_time', models.DateTimeField(auto_now=True, max_length=255, verbose_name='Time of Submission')),
                ('encryption_key_id', models.BigIntegerField(null=True, verbose_name='The encrypted key id')),
                ('encrypted_blob', models.TextField(null=True, verbose_name='The encrypted data')),
                ('security_token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Security token')),
                ('attachment_data', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='optional encrypted attachment for media files')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=16, verbose_name='report validation and identification in hex')),
                ('client_id', models.CharField(max_length=255, verbose_name='client anonymous identification in hex')),
                ('submission_time', models.DateTimeField(verbose_name='Time of Submission')),
                ('report_body', models.TextField(blank=True, null=True, verbose_name='The text of the report')),
                ('reporter_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='The name of the reporter')),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='The email of the reporter')),
                ('reporter_telegram', models.CharField(blank=True, max_length=1024, null=True, verbose_name='The telegram handle of the reporter')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=16, verbose_name='report validation and identification in hex')),
                ('client_id', models.CharField(max_length=255, verbose_name='client anonymous identification in hex')),
                ('encryption_key', models.CharField(default=b'0', max_length=64, verbose_name='The secret symmetric key to which the attachement is encrypted')),
                ('submission_time', models.DateTimeField(verbose_name='Time of Submission')),
                ('attachment_type', models.CharField(blank=True, max_length=8, null=True, verbose_name='The type of the attachment')),
                ('attached_data', models.FileField(upload_to=b'', verbose_name='The binary data which is need to be attached to the case')),
            ],
        ),
    ]
